server:
    AppVersion: 1.0.0
    Port: 5001
    Mode: Development
    ReadTimeout: 5
    WriteTimeout: 5
    SSL: false
    CtxDefaultTimeout: 12
    Debug: true

postgreSQL:
    Host: arjuna.db.elephantsql.com
    Port: 5432
    User: kgpkfsjq
    Password: RWOBbnsLzIdMdOFB424lbGRxSxiSAZNE
    DBName: kgpkfsjq

redis:
    Host: redis-12501.c1.ap-southeast-1-1.ec2.cloud.redislabs.com
    Port: 12501
    DB: 0
    Username: default
    Password: MovuXHLLp4bYE3uCc2q8Hgee3Amv7Kic
    MinIdleConns: 10
    PoolSize: 10
    PoolTimeout: 60

auth:
    JWTSecret: jwt_vukynpro_secret
    Expire: 3600
    Issuer: go_demo
    Audience: go_demo
