server:
  AppVersion: 1.0.0
  Port: 5001
  Mode: Development
  JwtSecretKey: secretkey
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: false
  CtxDefaultTimeout: 12
  Debug: false

postgreSQL:
    Host: localhost
    Port: 5432
    User: postgres
    Password: 123
    DBName: go_demo

auth:
    JWTSecret: 123456