server:
    AppVersion: 1.0.0
    Mode: Development
    ReadTimeout: 5
    WriteTimeout: 5
    SSL: false
    CtxDefaultTimeout: 12
    Debug: true

postgreSQL:
    Host: 
    Port: 5432
    User:
    Password:
    DBName:

redis:
    Host:
    Port:
    DB: 0
    Username:
    Password:
    PoolSize: 10
    PoolTimeout: 60

auth:
    JWTSecret: initiaRe_secret_key
    Expire: 3600
    Issuer: initiaRe_server
    Audience: initiaRe_client
