basePath: api/v1
definitions:
  models.User:
    properties:
      about:
        maxLength: 1024
        type: string
      address:
        maxLength: 250
        type: string
      avatar:
        maxLength: 512
        type: string
      birthday:
        maxLength: 10
        type: string
      city:
        maxLength: 24
        type: string
      country:
        maxLength: 24
        type: string
      created_at:
        type: string
      email:
        maxLength: 60
        type: string
      first_name:
        maxLength: 30
        type: string
      gender:
        maxLength: 10
        type: string
      id:
        type: integer
      last_name:
        maxLength: 30
        type: string
      login_date:
        type: string
      password:
        minLength: 6
        type: string
      phone_number:
        maxLength: 20
        type: string
      role:
        maxLength: 10
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    required:
    - first_name
    - last_name
    - password
    type: object
info:
  contact:
    email: vukynpro@gmailcom
    name: Vu Ky
    url: https://github.com/vukyn
  description: Example Golang REST API.
  title: Swagger Clean Architecture API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: register new user, returns user and token
      parameters:
      - description: First name
        in: body
        name: FirstName
        required: true
        schema:
          type: string
      - description: Last name
        in: body
        name: LastName
        required: true
        schema:
          type: string
      - description: Email
        in: body
        name: Email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: Password
        required: true
        schema:
          type: string
      - description: Gender
        in: body
        name: Gender
        required: true
        schema:
          type: string
      - description: City
        in: body
        name: City
        schema:
          type: string
      - description: Country
        in: body
        name: Country
        schema:
          type: string
      - description: Gender
        in: body
        name: Birthday
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Register new user
      tags:
      - Auth
swagger: "2.0"
