package constants

const (
	ERROR_CODE_BAD_REQUEST     = "BAD_REQUEST"
	ERROR_CODE_NOT_FOUND       = "NOT_FOUND"
	ERROR_CODE_UNAUTHORIZED    = "UNAUTHORIZED"
	ERROR_CODE_FORBIDDEN       = "FORBIDDEN"
	ERROR_CODE_INTERNAL_SERVER = "INTERNAL_SERVER_ERROR"
	ERROR_CODE_REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
)

const (
	ERROR_MESSAGE_EMAIL_ALREADY_EXISTS      = "EMAIL_ALREADY_EXISTS"
	ERROR_MESSAGE_INVALID_GENDER_TYPE       = "INVALID_GENDER_TYPE"
	ERROR_MESSAGE_USER_NOT_FOUND            = "USER_NOT_FOUND"
	ERROR_MESSAGE_INVALID_EMAIL_OR_PASSWORD = "INVALID_EMAIL_OR_PASSWORD"
	ERROR_MESSAGE_INTERNAL_SERVER_ERROR     = "INTERNAL_SERVER_ERROR"
	ERROR_MESSAGE_JSON_MARSHAL              = "JSON_MARSHAL"
	ERROR_MESSAGE_JSON_UNMARSHAL            = "JSON_UNMARSHAL"
)
